services:
  postgres:
    image: postgis/postgis:latest
    hostname: c4fd1d6fc275
    environment:
      POSTGRES_DB: streetservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
